<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE list [
        <!ELEMENT list (file)*>
        <!ELEMENT file (name, description)>
        <!ATTLIST file enabled (true|false) "true">
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        ]>
<list>
    <file>
        <name>AAAAAAAAAAAAA.WAV</name>
        <description>AAAAA</description>
    </file>
    <file>
        <name>Artist.WAV</name>
        <description>Artist</description>
    </file>
    <file>
        <name>Ass.WAV</name>
        <description>Ass we can</description>
    </file>
    <file>
        <name>Club.WAV</name>
        <description>Welcome</description>
    </file>
    <file>
        <name>College.WAV</name>
        <description>College boy</description>
    </file>
    <file>
        <name>Comming.WAV</name>
        <description>Cumming</description>
    </file>
    <file>
        <name>Fisting.WAV</name>
        <description>Fisting</description>
    </file>
    <file>
        <name>Like.WAV</name>
        <description>Like that hu?</description>
    </file>
    <file>
        <name>Penetration 1.WAV</name>
        <description>Penetration 1</description>
    </file>
    <file>
        <name>Penetration 2.WAV</name>
        <description>Penetration 2</description>
    </file>
    <file>
        <name>Power.WAV</name>
        <description>Power</description>
    </file>
    <file>
        <name>Take.WAV</name>
        <description>Take it boy</description>
    </file>
    <file>
        <name>WO.WAV</name>
        <description>Wo</description>
    </file>
    <file>
        <name>YEAAA.WAV</name>
        <description>Bitch slap</description>
    </file>
    <file>
        <name>Cum.WAV</name>
        <description>Certainly cum alright</description>
    </file>
    <file>
        <name>Atention.WAV</name>
        <description>Attention!</description>
    </file>
    <file>
        <name>Beat.WAV</name>
        <description>Beat me?</description>
    </file>
    <file>
        <name>LetsGo.WAV</name>
        <description>FUCKING DOOR</description>
    </file>
    <file>
        <name>Dicks.WAV</name>
        <description>Dicks</description>
    </file>
    <file>
        <name>Penetration3.WAV</name>
        <description>Penetration 3</description>
    </file>
    <file>
        <name>Shut.WAV</name>
        <description>Shut the fuck up</description>
    </file>
    <file>
        <name>Rip.WAV</name>
        <description>Rip the skin!</description>
    </file>
    <file>
        <name>Sorry.WAV</name>
        <description>Sorry for what</description>
    </file>
    <file>
        <name>Sun.WAV</name>
        <description>Suckshit</description>
    </file>
    <file>
        <name>Amazing.WAV</name>
        <description>Amazing</description>
    </file>
    <file>
        <name>Reach.WAV</name>
        <description>Reach out and play</description>
    </file>
    <file>
        <name>Point.WAV</name>
        <description>Wanna get on bottom?</description>
    </file>
    <file>
        <name>Two.WAV</name>
        <description>Two can play</description>
    </file>
    <file>
        <name>PullUp.WAV</name>
        <description>Pull up our pents</description>
    </file>
    <file>
        <name>Doing.WAV</name>
        <description>What the hell r u 2 doing?</description>
    </file>
    <file>
        <name>Fucked.WAV</name>
        <description>Why don't you get Fucked</description>
    </file>
    <file>
        <name>Tool.WAV</name>
        <description>Work that tool</description>
    </file>
    <file>
        <name>Challenges.WAV</name>
        <description>Challenges?</description>
    </file>
    <file>
        <name>Pants.WAV</name>
        <description>Rip my fucking pants!</description>
    </file>
</list>